import { useState } from "react";
import Head from "next/head";
import { FlexColumn, FlexRowAlignCenter } from "@/components/Flex";

export default function Home() {
  const [value, setValue] = useState("");
  const [messages, setMessages] = useState<string[]>([]);

  return (
    <>
      <Head>
        <title>DFlow Socket App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlexColumn
        as="main"
        style={{ justifyContent: "flex-end", height: "100vh" }}
      >
        {messages.map((message, i) => (
          <div key={message + i}>{message}</div>
        ))}
        <FlexRowAlignCenter style={{ marginTop: "auto", gap: "1rem" }}>
          <input
            style={{ width: "100%", height: "3rem", fontSize: "1.2rem" }}
            value={value}
            onChange={(e) => setValue(e.target.value)}
          />
          <button style={{ height: "3rem", fontSize: "1.2rem", width: "5rem" }}>
            Send
          </button>
        </FlexRowAlignCenter>
      </FlexColumn>
    </>
  );
}
